### ISSUE TITLE
how to add classes?

### ISSUE THREAD

**Issue by doveraudio** [patricktalmadge/bootstrapper#264]
How do i add a class to an element when creating it? I did not find anything in the docs or the code that jumped out at me. Maybe add a "class" method to prototypes?

**Comment by PatrickRose** [comment]
Use `withAttributes(['class' => 'something'])`

**Comment by PatrickRose** [comment]
Doesn't look to be actually, but I might add `addClass()` to the base class.

**Comment by doveraudio** [comment]
Awesome, thanks!
