### ISSUE TITLE
Brand logo in Navbar

### ISSUE THREAD

**Issue by Gormador** [patricktalmadge/bootstrapper#265]
I'm looking for a way to properly add a "brand" logo in a Bootstrapper Navbar, either in the middle (horizontally & vertically) or on the left before the brand.

Actual result of following code http://pastebin.com/4U7MHy4U
![navbarwithlogo_test](https://cloud.githubusercontent.com/assets/6118753/5646957/decb9062-9681-11e4-900f-4f8dabcce10a.png)

**Comment by PatrickRose** [comment]
Hi there,

(sorry for leaving this one - got mad busy) What's the html output you're expecting?

**Comment by Gormador** [comment]
Let me get back to you on that, my turn to be mad busy ;-) If I happen to forget about it, my apologies in advance...

**Comment by PatrickRose** [comment]
Any update on what you're expecting?

**Comment by Gormador** [comment]
Yep, sorry, as expected I didn't get to investigate the matter far enough to give you a proper answer. It's still in the back of my mind though...

**Comment by Francismori7** [comment]
Navbar::create(NAVBAR::NAVBAR_TOP)->withBrand(Image::circle(
                'book_flat_32x32.png',
                'circle'
              ));

**Comment by PatrickRose** [comment]
Just spotted that [brand images are now a thing](http://getbootstrap.com/components/#navbar-brand-image) so I'll work on this for the next release

**Comment by Gormador** [comment]
You are a saint.
Not sure if I'll have time to get back on my project any time soon, but still, thanks for your work :-)

**Comment by PatrickRose** [comment]
Tagged this morning.  Use `withBrandImage`.
