### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by gmsantosxl** [patricktalmadge/bootstrapper#266]
Since Laravel 5 is stable, is there any release in progress to support Laravel 5 ?

I've noted a `laravel-5` branch, but it seems outdated (last commit 2 months ago)

**Comment by PatrickRose** [comment]
I need to double check how packages work in L5 (since they broke in one commit and I haven't done any L5 work since then) but that's the plan

**Comment by PatrickRose** [comment]
So supporting laravel-5 in the `master` branch is potentially going to make me cry...

Here's a list of things that I've spotted so far. If you switch to using the `laravel-5` branch (`composer require patricktalmadge/bootstrapper:dev-laravel-5`) then you'll be able to load up Bootstrapper but there's a few things that need sorting

- [x] Update composer requirements
- [x] Update service provider to boot correctly
- [ ] Config will need changing slightly to account for Laravel 5's change in config management. I'll probably extract this out into an interface (which starts off the long term plan of extracting out the laravel dependencies so other frameworks can use this).

If you spot anything else, please drop another comment here
