### ISSUE TITLE
Radio button

### ISSUE THREAD

**Issue by heremiguel** [patricktalmadge/bootstrapper#269]
Hi Patrick, thank you for your library, very useful. 
I have one question which I don't find the answer yet :( I am sure you could help me:
How I do to set one state to active to a buttongroup?
 {{ ButtonGroup::radio([
Button::success('Anonymous')->extraSmall(),
Button::success('Visible')->extraSmall(),
 ]) }}

**Comment by PatrickRose** [comment]
Currently that's not possible. I forgot to do a clean up of the issues before I release 5.5 this morning so that'll be done as part of 5.6

**Comment by PatrickRose** [comment]
Fixed in f230130
