### ISSUE TITLE
Bootstrapper\Laravel4Config not found

### ISSUE THREAD

**Issue by supgeek-rod** [patricktalmadge/bootstrapper#270]
look follow,

![screen shot 2015-02-23 at 21 23 30](https://cloud.githubusercontent.com/assets/5748006/6328440/6eb30760-bba2-11e4-9739-ea45d1bfc8b2.png)
![screen shot 2015-02-23 at 21 25 28](https://cloud.githubusercontent.com/assets/5748006/6328448/8f21fb46-bba2-11e4-9dab-b0edfaf22651.png)

add `use Bootstrapper\Bridges\Config\Laravel4Config;` At `BootstrappedServiceProvider.php` file, it is back to normal

**Comment by PatrickRose** [comment]
I hate ServiceProviders...

Will fix later tonight.

On 23 February 2015 at 13:29, Rod <notifications@github.com> wrote:

> look follow,
>
> [image: screen shot 2015-02-23 at 21 23 30]
> <https://cloud.githubusercontent.com/assets/5748006/6328440/6eb30760-bba2-11e4-9739-ea45d1bfc8b2.png>
> [image: screen shot 2015-02-23 at 21 25 28]
> <https://cloud.githubusercontent.com/assets/5748006/6328448/8f21fb46-bba2-11e4-9dab-b0edfaf22651.png>
>
> add 'use Bootstrapper\Bridges\Config\Laravel4Config;AtBootstrappedServiceProvider.php`file,
> it is back to normal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/patricktalmadge/bootstrapper/issues/270>.
>



-- 
Regards

Patrick Rose

**Comment by PSutton3756** [comment]
I believe the fix to this issue may have caused another issue. This was with Larevel 4.2 if that matters.

Version 5.5.1 (when running composer update)
Exception: Declaration of Bootstrapper\Image::addClass() should be compatible with Bootstrapper\RenderedObject::addClass(array $classes)

**Comment by PatrickRose** [comment]
That's a separate issue. I'll deal with that now.

**Comment by PatrickRose** [comment]
Fixed in 7bfc5a3 (5.5.2)
