### ISSUE TITLE
Add the ability to add class to a Panel in Accordion

### ISSUE THREAD

**Issue by netm** [patricktalmadge/bootstrapper#272]
Hi there, does anybody know if it is possible to add a class to an Accordion Panel?

Ideally something like:

        $panels[] = [
            'title'    => 'Panel title,
            'contents' => 'Panel contents',
            'class' => 'panel-x'
        ];

Where the class turned up attached to the div that is currently .panel

Love Bootstrapper!

**Comment by PatrickRose** [comment]
Use the `attributes` array key instead.

```php
$panel = [
    'title' => "Foo,
    "content" = "Bar",
    "attributes" => [
        "class" => "some-class"
    ]
];
```
