### ISSUE TITLE
Facade conflict?

### ISSUE THREAD

**Issue by harrisoftware** [patricktalmadge/bootstrapper#279]
ErrorException in FormBuilder.php line 82:
Argument 1 passed to Illuminate\Html\FormBuilder::__construct() must be an instance of Illuminate\Html\HtmlBuilder, instance of Collective\Html\HtmlBuilder given, called in /Users/****/Sites/****/vendor/patricktalmadge/bootstrapper/src/Bootstrapper/BootstrapperL5ServiceProvider.php on line 210 and defined (View: /Users/****/Sites/****/resources/views/admin/forms/fromModel.blade.php)

I'm guessing this is a conflict between bootstrapper and the HTML package from LaravelCollective which both use a Form Facade???

I'm new to this tho so I could be wrong. Any suggestions?

**Comment by PatrickRose** [comment]
I see the issue but I can't fix for a while.

Basically we expect an instance of Laravel's HTML component but you have something else bound instead (which is why people should prefix their IoC bindings, but that's a rant for another day).

I'll take a look at their code and see whether I can add a compatibility fix.

**Comment by harrisoftware** [comment]
Well, until you fix it, i have changed the alias for the laravelcollective's restoration of the HTML and Form functionality of Laravel 4 Facade to 'FORM' from 'Form', so now I can use FORM and your Form in the same form - best of both world's (so far)

**Comment by PatrickRose** [comment]
Sorry for the delay on this - I've finally had a spare day to work on things.

I need to know more about how the Collective is working and what the plan is and when I checked a month ago I didn't find much about what the aim actually is.

**Comment by FabryB** [comment]
Please checkout my prposed fix, should work for everyone
