### ISSUE TITLE
horizontal_open() does not exist - issue with Laravel5

### ISSUE THREAD

**Issue by kudi** [patricktalmadge/bootstrapper#284]
Hi, I have installed Laravel5 and added bootstrapper as per github guidelines. Trying to use horizontal_open() in a blade but got this error message.  "ErrorException in Macroable.php line 87:
Method horizontal_open does not exist." Any help would be appreciatedl!. Also is there any documentation on how to code using bootstrapper in laravel5.

**Comment by PatrickRose** [comment]
Hi there! 

Could you give me a snippet of how you're using it?

The documentation we have is at http://bootstrapper.eu1.frbit.net/ - there's not enough of a fundamental difference of using it in L5 and L4 so those docs should continue to be correct.

**Comment by PatrickRose** [comment]
Hang on... horizontal_open was in Bootstrapper V4, but not in Bootstrapper V5. You should be using "horizontal"
