### ISSUE TITLE
BootstrapperL5ServiceProvider exception message is off

### ISSUE THREAD

**Issue by FliesMoreCeilings** [patricktalmadge/bootstrapper#286]
BootstrapperL5ServiceProvider threw this exception for me while I was using Laravel 4.
"This Service Provider doesn't support Laravel 5 - please use
                Bootstrapper\\BootstrapperL5ServiceProvider"

It appears to be recommending itself over itself and suggests I'm using Laravel 5. It caused some confusion.

**Comment by PatrickRose** [comment]
I'll hopefully have time to update today

BootstrapperL5ServiceProvider threw this exception for me while I was using
Laravel 4.
"This Service Provider doesn't support Laravel 5 - please use
Bootstrapper\BootstrapperL5ServiceProvider"

It appears to be recommending itself over itself and suggests I'm using
Laravel 5. It caused some confusion.

—
Reply to this email directly or view it on GitHub
<https://github.com/patricktalmadge/bootstrapper/issues/286>.
