### ISSUE TITLE
Composer not updating Bootstrapper - Laravel 4.2

### ISSUE THREAD

**Issue by netm** [patricktalmadge/bootstrapper#289]
Hi,

I am using Laravel 4.2 and I can tell my Bootstrapper is old because an old bug with Select box classes is still in src/Bootstrapper/Form.php:

    public function select($name, $list = array(), $selected = null, $options = array())
    {
        $options['class'] = isset($attributes['class']) ? self::FORM_CONTROL . ' ' . $attributes['class'] : self::FORM_CONTROL;

        return parent::select($name, $list, $selected, $options);
    }

My composer looks like this:

    "patricktalmadge/bootstrapper": "~5",

Yet when I run composer update I do not get the most recent version, running composer show -i gives me:

    patricktalmadge/bootstrapper      5.x-dev 4dfea13

Any ideas on what I am doing wrong?

Many thanks

**Comment by PatrickRose** [comment]
Could you dump your entire composer.json? There might be some weird conflicts.

**Comment by netm** [comment]
Hi Patrick - thanks, here you go

{
		"repositories": [
		    {
		        "type": "composer",
		        "url": "http://packages.cartalyst.com"
		    }
		],
		"name": "laravel/laravel",
		"description": "The Laravel Framework.",
		"keywords": ["framework", "laravel"],
		"require": {
			"laravel/framework": "4.2.17",
			"cartalyst/sentry": "2.1.*",
			"umpirsky/country-list": "1.0.0",
			"greggilbert/recaptcha": "1.1.*",
			"tecnick.com/tcpdf": "6.0.*",
			"baum/baum": "1.0.*",
			"vtalbot/markdown": "1.*",
			"pda/pheanstalk": "2.0.*",
		  	"maatwebsite/excel": "~1.3.0",
		  	"patricktalmadge/bootstrapper": "~5",
			"barryvdh/laravel-debugbar": "~1.8"
		},
		"autoload": {
			"classmap": [
				"app/commands",
				"app/controllers",
				"app/models",
				"app/database/migrations",
				"app/database/seeds",
				"app/tests/TestCase.php",
				"app/Services"
			],
	        "psr-0": {
	        	"App/Controllers": "app/controllers",
	        	"App/Models": "app/models",
	            "App/Services": "app/Services"
	        }
		},
		"scripts": {
			"post-install-cmd": [
				"php artisan optimize"
			],
			"pre-update-cmd": [
				"php artisan clear-compiled"
			],
			"post-update-cmd": [
				"php artisan optimize"
			],
			"post-create-project-cmd": [
				"php artisan key:generate"
			]
		},
		"post-update-cmd": [
		],
		"config": {
			"preferred-install": "dist"
		},
		"minimum-stability": "dev"
	}

**Comment by PatrickRose** [comment]
I'll boot up something in a second - but another oddity seems to be that the sha1 hash composer gives doesn't seem to exist...

Have you tried deleting your vendor directory and composer.lock?

**Comment by PatrickRose** [comment]
Aha! It's the fact we have a branch called v5 - packagist is picking that up and assuming that it should be using that branch when your minimum stability is dev. I've deleted the branch now and it downloaded the correct version just now.
