### ISSUE TITLE
Form::select does not use the custom attribute

### ISSUE THREAD

**Issue by ryanbayona** [patricktalmadge/bootstrapper#290]
Using Bootstrapper for L4, under bootstrapper/src/Bootstrapper/Form.php line 93.

Form::select uses $attributes instead of $options which causes Form::select to ignore custom class attributes passed into it.

**Comment by PatrickRose** [comment]
Possibly related to #289.

Can you run composer show -i and let me know which version of bootstrapper you have installed?

**Comment by ryanbayona** [comment]
patricktalmadge/bootstrapper      5.x-dev 4dfea13       Twitter Bootstrap markup generator

**Comment by PatrickRose** [comment]
Yup. If you run composer update again it should give you 5.7.0 - composer assumes you wanted the v5 branch if your stability is set to dev. That branch has now been deleted so it won't pick it up. You may need to delete your composer.lock and vendor directory if composer is silly.

**Comment by ryanbayona** [comment]
Yep that worked. Thanks!
