### ISSUE TITLE
Laravel 5 - Forms dont work

### ISSUE THREAD

**Issue by yswery** [patricktalmadge/bootstrapper#292]
```
ErrorException in FormBuilder.php line 82:
Argument 1 passed to Illuminate\Html\FormBuilder::__construct() must be an instance of Illuminate\Html\HtmlBuilder, instance of Collective\Html\HtmlBuilder given, called in /Users/user/Code/vendor/patricktalmadge/bootstrapper/src/Bootstrapper/BootstrapperL5ServiceProvider.php on line 210
```

In laravel 5 Illuminate\Html\FormBuilder has been removed and no longer used, instead there is "laravelcollective/html" to get this to work I needed to change the name space on

https://github.com/patricktalmadge/bootstrapper/blob/master/src/Bootstrapper/Form.php#L6

From `Illuminate\Html` to `Illuminate\Html`

Any clean way this could be fixed on the package? Would be pretty awesome!

**Comment by ReLexEd** [comment]
Have you seen: https://github.com/patricktalmadge/bootstrapper/issues/279 ? ;-)

**Comment by PatrickRose** [comment]
Looks like I forgot to mark `laravelcollective/html` as a conflict in the last release. Bleh.

Laravel 4 support will last until PHP 5.4 hits EOL (next year) or Bootstrap 4.0 is released (no ETA that I've found).

I think in the meantime I'll add an additional binding that we know will return `Illuminate\Html\HtmlBuilder`

**Comment by yswery** [comment]
@ReLexEd Opps you are totally right, missed that one. This is a dupe

@PatrickRose So basically we are leaving this broken for the *current* laravel version in the meanwhile until next year perhaps? What are your thoughts about perhaps updating your `laravel-5` branch and having that continue as a L5 only branch that will be fully functional and thus being able to continue support for L4 also at the same time. Or better yet the other way round... master == L5, and a different branch for the old and non-current L4? 

Just a thought...

**Comment by PatrickRose** [comment]
@yswery I'll make sure we're returning the correct HTML in the next patch release - no ETA on that (I'm really busy for the next week or so). I took the position that laravelcollective/html wasn't the "official" way to be using the html component, but I see they've updated the docs to point people towards the collective's version.

**Comment by FabryB** [comment]
Please checkout my prposed fix, should work for everyone
