### ISSUE TITLE
In Laravel 5.1 lines that adding to config/app.php change

### ISSUE THREAD

**Issue by Timures** [patricktalmadge/bootstrapper#296]
Hello, 
If that beatyfull pachage don't work for someone user L5.1 - 
In In Laravel 5.1 lines that adding to config/app.php changed:
from 'Bootstrapper\BootstrapperL5ServiceProvider',
 to Bootstrapper\BootstrapperL5ServiceProvider::class,
--------------
'Accordion' => 'Bootstrapper\Facades\Accordion',
'Alert' => 'Bootstrapper\Facades\Alert',
'Badge' => 'Bootstrapper\Facades\Badge',
'Breadcrumb' => 'Bootstrapper\Facades\Breadcrumb',
'Button' => 'Bootstrapper\Facades\Button',
'ButtonGroup' => 'Bootstrapper\Facades\ButtonGroup',
'Carousel' => 'Bootstrapper\Facades\Carousel',
'ControlGroup' => 'Bootstrapper\Facades\ControlGroup',
'DropdownButton' => 'Bootstrapper\Facades\DropdownButton',
'Form' => 'Bootstrapper\Facades\Form',
'Helpers' => 'Bootstrapper\Facades\Helpers',
'Icon' => 'Bootstrapper\Facades\Icon',
'InputGroup' => 'Bootstrapper\Facades\InputGroup',
'Image' => 'Bootstrapper\Facades\Image',
'Label' => 'Bootstrapper\Facades\Label',
'MediaObject' => 'Bootstrapper\Facades\MediaObject',
'Modal' => 'Bootstrapper\Facades\Modal',
'Navbar' => 'Bootstrapper\Facades\Navbar',
'Navigation' => 'Bootstrapper\Facades\Navigation',
'Panel' => 'Bootstrapper\Facades\Panel',
'ProgressBar' => 'Bootstrapper\Facades\ProgressBar',
'Tabbable' => 'Bootstrapper\Facades\Tabbable',
'Table' => 'Bootstrapper\Facades\Table',
'Thumbnail' => 'Bootstrapper\Facades\Thumbnail',

to 
 # ...
        'Accordion' => Bootstrapper\Facades\Accordion::class,
        'Alert' => Bootstrapper\Facades\Alert::class,
        'Badge' => Bootstrapper\Facades\Badge::class,
        'Breadcrumb' => Bootstrapper\Facades\Breadcrumb::class,
        'Button' => Bootstrapper\Facades\Button::class,
        'ButtonGroup' => Bootstrapper\Facades\ButtonGroup::class,
        'Carousel' => Bootstrapper\Facades\Carousel::class,
        'ControlGroup' => Bootstrapper\Facades\ControlGroup::class,
        'DropdownButton' => Bootstrapper\Facades\DropdownButton::class,
        'Form' => Bootstrapper\Facades\Form::class,
        'Helpers' => Bootstrapper\Facades\Helpers::class,
        'Icon' => Bootstrapper\Facades\Icon::class,
        'InputGroup' => Bootstrapper\Facades\InputGroup::class,
        'Image' => Bootstrapper\Facades\Image::class,
        'Label' => Bootstrapper\Facades\Label::class,
        'MediaObject' => Bootstrapper\Facades\MediaObject::class,
        'Modal' => Bootstrapper\Facades\Modal::class,
        'Navbar' => Bootstrapper\Facades\Navbar::class,
        'Navigation' => Bootstrapper\Facades\Navigation::class,
        'Panel' => Bootstrapper\Facades\Panel::class,
        'ProgressBar' => Bootstrapper\Facades\ProgressBar::class,
        'Tabbable' => Bootstrapper\Facades\Tabbable::class,
        'Table' => Bootstrapper\Facades\Table::class,
        'Thumbnail' => Bootstrapper\Facades\Thumbnail::class,

------------------
Please, add to Wiki
Thanks. (sorry for my English)

**Comment by PatrickRose** [comment]
I've found the PR where that's mentioned (laravel/laravel#3402).

'Foo\Bar' is equivalent to Foo\Bar::class anyway - if you want to use that syntax then feel free. I don't think it needs updating here

**Comment by tortuetorche** [comment]
FYI: The `Foo\Bar::class` is only compatible with PHP >= 5.5, more info [here](http://php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name).
