### ISSUE TITLE
missing navbar-right on navigation

### ISSUE THREAD

**Issue by iicolsandersii** [patricktalmadge/bootstrapper#298]
Patrick,

In the past with the Bootstrap navbar, I have been able to re-position my dropdown to the right side of the nav-bar by using 'navbar-right'.

I have not been able to figure out how to accomplish this using bootstrapper. I have tried Navigation::setPosition('right'), and Navigation::NAVBAR_RIGHT, no luck.

Navbar::withBrand('example.com', '/')
    ->inverse()
    ->withContent(Navigation::links([
        [
          'categories',
          [
              [
                  'link' => '/code',
                  'title' => 'IT'
              ],
              [
                  'link' => '/code',
                  'title' => 'code'
              ],
              Navigation::NAVIGATION_DIVIDER,
              [
                  'link' => '/admin',
                  'title' => 'admin'
              ],
          ]
      ]
      ]))

Thanks in advance!
-Josh

**Comment by PatrickRose** [comment]
Sorry for the delay!

Could you give me the HTML you're expecting and what Bootstrapper is providing?

**Comment by iicolsandersii** [comment]
Just double checked the code again, and I added ->right() at the end of withContent...

Navbar::withBrand('example.com', '/')
  ->inverse()
  ->withContent(Navigation::links(
  [
    [
      'link' => '#',
      'title' => 'Home',
    ],
  ])->right())

And I get this result!

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Home</a></li>
      </ul>
</div>

I am using the lastest build, may have been fixed or I totally missed where to out right().

Thanks :)
