### ISSUE TITLE
Striped Bordered Table

### ISSUE THREAD

**Issue by rawrmonstar** [patricktalmadge/bootstrapper#299]
It is impossible to set a table to both striped and bordered when this is possible in bootstrap:
`<table class="table table-bordered table-striped">`

if you use both `striped()` and `bordered()` methods on the generated table, the method called last is the way the table is generated.

**Comment by PatrickRose** [comment]
Good spot, cheers. 

Might have the chance to update this tonight

**Comment by rawrmonstar** [comment]
Here is a pull request https://github.com/patricktalmadge/bootstrapper/pull/301 that should fix the issue.

**Comment by PatrickRose** [comment]
Closed by #301
