### ISSUE TITLE
'Active' Class on Navbar Links

### ISSUE THREAD

**Issue by silverskymedia** [patricktalmadge/bootstrapper#304]
I am creating a Navbar. It creates it fine, but it's not applying the "active" class. From I understood it should do it automatically. Am I wrong? Thanks.

**Comment by PatrickRose** [comment]
Hi

Can you give me a snippet?

**Comment by silverskymedia** [comment]
Here is a simple snippet of what I’m trying.

{!!
		Navbar::withBrand(‘Brand' , '/')
			->withContent(Navigation::links([
				[
					'link' => '/',
					'title' => 'Home'
				],
				[
					'link' => 'about',
					'title' => 'About Us'
				]

			]))
	!!}	


Thanks.

**Comment by PatrickRose** [comment]
You need to use route('foo') instead - we do a full match for the active links.

**Comment by silverskymedia** [comment]
Thanks for your help. I’m not sure what you mean by “instead.” What does route(‘foo’) replace?

Thanks.

**Comment by PatrickRose** [comment]
Replace `'link' => 'about'` with `'link' => route('about')`.

If you take a look at [Bootstrapper\Navigation](https://github.com/patricktalmadge/bootstrapper/blob/master/src/Bootstrapper/Navigation.php#L304-L305) you'll see we do `$this->url->current() == $item['link']`. If you just use `'link' => 'about'` then `$this->url->current()` will return something like `http://your.dev.site/about` which won't equal `about`

**Comment by silverskymedia** [comment]
I tried that, it doesn’t work for me. It tells me that my route is not defined. Here is how I defined my route:

Route::get('about', 'PagesController@about’);

Is this not correct?

Thanks,
Nate

**Comment by PatrickRose** [comment]
Ah - if you're not using [Named Routes](http://laravel.com/docs/5.1/routing#named-routes) then you should be using `url('about')`

**Comment by silverskymedia** [comment]
OK, great, it's working. Thanks for your help. Would you recommend I use a
Named Route?

**Comment by PatrickRose** [comment]
I find named routes to be much easier to work with, mainly because `route('foo')` is more readable than `url('foo')`, but it's your app :-)
