### ISSUE TITLE
Upgrade Guide?

### ISSUE THREAD

**Issue by austenc** [patricktalmadge/bootstrapper#306]
Is there an upgrade guide available for upgrading from Bootstrapper 4 to v5? I've got a project on Laravel 4.2 and boostrapper `4.1.*` that I'd like to upgrade, so I'm trying to figure out if it'll be a tough transition or not? 

Thank you to anyone who can shed some light on this and point me in the right direction!

**Comment by PatrickRose** [comment]
The docs for v5 (http://bootstrapper.eu1.frbit.net) have some information.

Most of the changes revolve around making the api more fluid and readable.
If anything is painful or not explained then let me know!

**Comment by austenc** [comment]
Thank you @PatrickRose, the http://bootstrapper.eu1.frbit.net/migration page is exactly what I was looking for!

**Comment by austenc** [comment]
@PatrickRose just a heads up -- there's no right hand menu item for `Icons` in the documentation. It also appears that you can no longer do something like `Icon::asterisk(['class' => 'text-danger'])` to give the icon a contextual class? Other than that, it appears my upgrade has gone fine!
