### ISSUE TITLE
Specify data attributes (or other) on Button?

### ISSUE THREAD

**Issue by austenc** [patricktalmadge/bootstrapper#307]
Is there a way to specify data attributes or other additional attributes on a given button? In older versions, it was done like `Button::success('My text', ['data-something' => 'my data'])`. I realize other attributes are available via chainable methods such as `Button::success('Yay!')->submit()`.... but I didn't see mention of custom attributes or data attributes in the docs (hopefully I just missed this?)

If this isn't supported, would a pull request be considered to add this functionality? I could see it being very useful for specifying a button name directly, additional classes, or additional data attributes.

Edit for clarity:

What I'm after is something to produce html like this: `<button data-something="my data">` or `<button name="xyz">`

**Comment by PatrickRose** [comment]
Pretty much every class has a withAttributes method which should do what
you want - Button definitely does.

**Comment by austenc** [comment]
Excellent, I just didn't see that in the button docs but I see it elsewhere now. I figured there was something in place since this is a common task! Thank you!
