### ISSUE TITLE
Laravel5 bug

### ISSUE THREAD

**Issue by boscorelly** [patricktalmadge/bootstrapper#308]
Hi,

when trying to install in laravel5 :

```
> php artisan optimize
PHP Fatal error:  Undefined constant 'Bootstrapper\BootstrapperL5ServiceProvider' in /home/sites/xxxx/site/config/app.php on line 159
Script php artisan optimize handling the post-update-cmd event returned with an error

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Error Output: PHP Fatal error:  Undefined constant 'Bootstrapper\Bootstrapper
  L5ServiceProvider' in /home/sites/xxxx/site/config/app.php on line 159
```

**Comment by boscorelly** [comment]
PHP 5.6.19-0+deb8u1

**Comment by PatrickRose** [comment]
That looks like laravel being silly. What's your app.php look like on that line?

**Comment by boscorelly** [comment]
I'm new to laravel.
It's a fresh install and i've followed the guide at laravel website.

Just added the line you are giving on the project :

`'Bootstrapper\BootstrapperL5ServiceProvider',`

**Comment by boscorelly** [comment]
you can see here : http://pastebin.com/ii0sjwkV

I also have the sme problem with the following line of bootstrapper.

**Comment by PatrickRose** [comment]
Your app file has Bootstrapper\BootstrapperL5ServiceProvider - not
'Bootstrapper\BootstrapperL5ServiceProvider' (ie you haven't given the
class name as a php string).

You could also change it to
Bootstrapper\BootstrapperL5ServiceProvider::class and it'll work.

**Comment by boscorelly** [comment]
pffff it's not a bug, it's a noob :D

I was thinking the quotes are not needed, but they are.

Thanks for your answer !
