### ISSUE TITLE
Alternative alias configuration..

### ISSUE THREAD

**Issue by mpathy** [patricktalmadge/bootstrapper#309]
You suggest a set of aliases for your project..
Many of them are in conflict with other projects aliases..
(laravel collective uses form, intervention image uses image)

Its maybe better to give them an prefix in your documentation, so newbies dont run into problems so fast.. BSImage, BSForm, BSTabel

**Comment by PatrickRose** [comment]
By that token all the other projects should do the same ;-) 

I don't think they should. Our Form alias historically overwrote the one provided by Laravel and this is a similar situation.
