### ISSUE TITLE
How do I create input group using the InputGroup Facade in Laravel 5 ?

### ISSUE THREAD

**Issue by cyrusolu** [patricktalmadge/bootstrapper#313]

**Comment by PatrickRose** [comment]
I don't understand the problem - what have you tried and what isn't working?

**Comment by cyrusolu** [comment]
I want to create this 
`<div class="form-group control-width-normal">
												<div class="input-group date" id="demo-date">
													<div class="input-group-content">
														<input type="text" class="form-control">
														<label>Datepicker</label>
													</div>
													<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>`

**Comment by PatrickRose** [comment]
The [documentation](http://bootstrapper.eu1.frbit.net/base-css) is linked in the readme.

```php
InputGroup::withContents(Form::date('date'))->append('<i class="fa fa-calendar"></i>'>;
```

should be right - though you may need to tinker.
